import type { Metadata } from 'next'

import { Rubik } from 'next/font/google'

import './globals.css'
import { Toastify } from '@/_layouts'

const rubik = Rubik({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['arabic'],
})

export const metadata: Metadata = {
	title: 'Template',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${rubik.className} flex h-screen flex-col`}>
				{children}
				<Toastify />
			</body>
		</html>
	)
}
