import './globals.css'

import type { Metadata } from 'next'

import { Rubik } from 'next/font/google'
import { getLangDir } from 'rtl-detect'
import { getLocale } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'

import { MainWrapper } from '@/_layouts'

const rubik = Rubik({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['arabic'],
})

export const metadata: Metadata = {
	title: 'Template',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const locale = await getLocale()
	const direction = getLangDir(locale)

	return (
		<html dir={direction} lang={locale}>
			<body className={`${rubik.className}`}>
				<NextIntlClientProvider>
					<MainWrapper>{children}</MainWrapper>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
